[metadata]
name = "Simple Test"
version = "1.0"

[runtime]
duration_seconds = 60
vus = 10

[target]
base_url = "http://localhost:8080"
http_version = "http1.1"

[[requests]]
name = "get_root"
method = "GET"
path = "/"
timeout_ms = 1000

[schedule]
type = "constant"
vus = 10
